spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 5ca1c108-a1be-4bf7-8804-a38b619ed99d
      config:
        server-addr: 127.0.0.1:8848
#        namespace: 5ca1c108-a1be-4bf7-8804-a38b619ed99d
    gateway:
      routes:
        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

server:
  port: 80